spring:
  application:
    name: "DivitBot"
  datasource:
    url: "jdbc:postgresql://localhost:5432/otrs"
    username: ""
    password: ""
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: ""
    password: ""
    protocol: "smtp"
    properties:
      mail.transport.protocol: "smtp"
      mail.smtp.auth: "true"
      mail.smtp.starttls.enable: "true"
      mail.smtp.ssl.trust: "*"
      mail.debug: "true"


bot:
  config:
    username: ""
    token: ""
  templates:

    text:
      new-user-message: |
        ⚠️ Перед началом работы необходимо заполнить анкету 
        
        *• ФИО 
        • Номер телефона
        • Почта
        • Компания*
        
        Анкета заполняется один раз
        *В будущем вы сможете изменить данные*
      fill-full-name: "✉️ Введите ФИО"

      fill-phone: "✉️ Введите Номер телефона"

      fill-email: "✉️ Введите почту для связи"

      fill-company: "✉️ Введите название вашей компании"

      press-button-to-start-filling-questionnaire: "🔽 Нажмите *Заполнить анкету* 🔽"

      describe-problem: "📋 Опишите проблему"

      request-processing: "⏳ Ваш запрос обрабатывается"

      request-processed: |
        🟢 Запрос отправлен!
        *Поддержка свяжется с вами в течении 15 минут!*"

      start-editing-data: |
        ✏️ ️Редактирование персональных данных
        
        *Для отмены нажмите кнопку ниже 🔽*

      stop-editing-data: "✅️ Редактирования данных отменено"




